spring.application.name=datelocator-be

spring.datasource.url=jdbc:postgresql://localhost:5433/datelocator-db
spring.datasource.username=datelocator
spring.datasource.password=datelocator
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.com.datelocator.datelocatorbe=DEBUG
server.error.include-message=always
server.error.include-stacktrace=always
server.address=0.0.0.0
server.port=8080

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://10.0.2.2:8081/realms/datelocator}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://localhost:8081/realms/datelocator/protocol/openid-connect/certs}
app.security.jwt.accepted-issuers=${KEYCLOAK_ACCEPTED_ISSUERS:http://10.0.2.2:8081/realms/datelocator,http://localhost:8081/realms/datelocator}
app.security.swagger.issuer-uri=${KEYCLOAK_SWAGGER_ISSUER_URI:http://localhost:8081/realms/datelocator}

# Swagger UI OAuth2 settings
springdoc.swagger-ui.oauth.client-id=datelocator-api
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true