services:
  postgres:
    image: postgres:latest
    container_name: datelocator-postgres
    environment:
      POSTGRES_USER: datelocator
      POSTGRES_PASSWORD: datelocator
      POSTGRES_DB: datelocator-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: